pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                git branch: 'main', credentialsId: 'akshatjain04', url: 'https://github.com/akshatjain2982000/Graphql.git/api-gateway_api-gateway'
            }
        }
    }
}
